---
abstract: 'Interface to read and modify Apache .htpasswd files'
author:
  - 'David Kamholz <dkamholz@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Authen-Htpasswd
no_index:
  directory:
    - t
    - inc
requires:
  Class::Accessor::Fast: 0
  Crypt::PasswdMD5: 0
  Digest: 0
  Digest::SHA1: 0
  IO::LockedFile: 0
  Scalar::Util: 0
version: 0.171
