--- #YAML:1.0
name: Authen-Htpasswd
version: 0.12
author:
  - David Kamholz <davekam at pobox dot com>
abstract: interface to read and modify Apache .htpasswd files
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
